# Mathematics of Finance

## Percentages

**Index number** The scale factor of a variable measured from the base year multiplied by 100.

**Inflation** The percentage increase in the level of prices over a $12$-month period.

**Nominal data** Monetary values prevailing at the time that they were measured.

**Real data** Monetary values adjusted to take inflation into account.

## Compound interest

**Simple interest** The interest which is paid directly to the investor instead of being added to the original amount.
$$S=P\times(1+rt)$$

**Compound interest** The interest which is added on to the initial investment, so that this will itself gain interest in subsequent time periods.
$$S=P\times(1+r)^t$$

**Continuous compounding** The limiting value when interest is compounded with ever-increasing frequency.
$$S=P\times e^{rt}$$

**Annual percentage rate** The equivalent annual interest paid for a loan, taking into account the compounding over a variety of time periods.

**Principal** The value of the original sum invested.

**Future value** The final value of an investment after one or more time periods.

## Geometric series

**Arithmetic progression** A sequence of numbers with a constant difference between consecutive terms; the $n$th term takes the form, $a+bn$.

**Geometric progression** A sequence of numbers with a constant ratio between consecutive terms; the $n$th term takes the form of $ar^{n-1}$. 

**Geometric ratio** The constant multiplier $r$ in a geometric series.

**Formula of sum of geometric series** 
$$\sum_{i=1}^n ar^{i-1}=a\left(\frac{r^n-1}{r-1}\right)$$

**Sinking fund** A fixed sum of money saved at regular intervals which is used to fund some future financial commitment.

## Investment appraisal

**Net present value (NPV)** The present value of a revenue flow minus the original cost. NPV is preferred than IRR sometimes.

**Internal rate of return (IRR)** The interest rate for which the net present value is zero

**Discount rate** The interest rate that is used when going backwards in time to calculate the present value from a future value.

**Discounting** The process of working backwards in time to find the present values from a future value.

**Annuity** A lump-sum investment designed to produce a sequence of equal regular payments over time.








