
```{r include=FALSE}
knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
```

# Chapter 3 {- #s3}

## Multiple choice questions {- #mq3}

Starting from Chapter 3, we will not provide the solutions to the multiple choice questions. If you have any problems, please ask me or tutor via email or wechat.

## Examination questions {- #eq3}

### Question 1 {- #eq3.1}

(a)$$ S(5)=4000(1 + \frac{0.04}{4})^{5\times4} \\
          \approx 4880.76$$
(b)
$$ S(5)=4000e^{\delta t} \\
       =4000e^{0.04 \times5}\\
          \approx 4885.61 $$ 
(c)$$ 4000(1 + \frac{0.04}{4})^{5\times4}=4000(1+i)^5  $$
$$ i \approx 0.0406 $$
$$ 4000e^{0.04\times5}=4000(1+i')^5  $$
$$ i' \approx 0.0408 $$ 
(d)$$ S(t) = 4500\\
           = 4000e^{t \times 0.04}$$
   $$ t \approx 2.94 $$

### Question 2 {- #eq3.2}

(a)$$ 1+i = (1+0.024)(1-0.049) $$
$$  i \approx -0.0262 $$
Thus the film's sales fall by 2.62% over the whole year.

(b) $$  S(3) = 700 \\
             = P(1 + \frac{0.048}{2})^{3 \times 2}) $$
    $$ P \approx 607.15 $$
(c)$$ P \times m \frac{1-(1+ i)^{-t} }{i} \\
     =1500 \times12 \frac{1-(1+0.06)^{-25} }{0.06} \\
     \approx 230000 $$

### Question 3 {- #eq3.3}

(a)(i)  $$  4000(1-0.1)^1+350 = 3950 $$

(ii) $$ 3950(1-0.1)^1+350 = 3905  $$

(b) $$ 3500 + 500(0.9) = 3950 $$
So N=1.

(c)It will tend to 3500 in the long-run, as when the number of trees is over 3500, it will decrease by 10% and increase by 350 every year, so it is reduced as a whole. Until it decreases to around 3500, the reduced number of trees is balanced with the increased number, thus it will tend to 3500 in the long-run.

### Question 4 {- #eq3.4}

(a)$$ \frac{6\times35+15\times15}{5\times35+12\times15} \\
     =\frac{87}{71}\\
     \approx 1.2254$$
Thus the Laspeyres index is 122.54

(b)$$ \frac{6\times30+15\times20}{5\times35+12\times15} \\
     =\frac{96}{71}\\
     \approx 1.3521$$
Thus the Paasche index is 135.21

(c)It is omitted , you cn refer to the answers in the textbook.

### Question 5 {- #eq3.5}

As for A：
$$ 10000(1+i_A)^3=11500 $$
$$ i_A = 0.0477 $$
As for B：
$$ 10000(1+i_B)^4=12100 $$
$$ i_B = 0.0488 $$
As for the advice, it is omitted , you cn refer to the answers in the textbook.

### Question 6 {- #eq3.6}

(a)

Suppose the GDP of country B is x now, then the GDP of country B is 2x now, and suppose the GDP of country B will exceed that of country A after n years, then we can get :
$$ x(1+0.04)^n > 2x(1+0.01)^n $$
$$ n > 24$$
So the GDP of country B will exceed that of country A after 24 years.

(b)
(i)$$ 4000(1.004)^n-250\times100(1.004^n-1) = 0 $$
$$ n \approx 44 $$


(ii) $$ 4000(1.004)^12-250x(1.004^12-1) = 0 $$
$$ x \approx 342.06 $$
(iii) $$ 4000(1.004)^n-250\times16(1.004^n-1)\\
        =4000$$
When x=16, the outstanding debt is a constant, which is 4000.

### Question 7 {- #eq3.7}

(a) $$ S = P(1+i)^n  $$
(i)$$ S = 4000(1+0.03)^6 \approx 4776.21  $$
(ii)$$ 3149.28 = P(1+0.08)^3 $$
$$ P \approx 2500  $$
(iii) $$ 5283.92 = 5000(1+r/100)^2 $$
$$ r=2.8 $$
attention: as it is **r%**, so i = r/100.

(iv) $$ 120788.25 = 75000(1+0.1)^n $$
$$ n = 5 $$

(b)(i)
$$ PV=P \frac{1-(1+i)^{-n}}{i} \\
     =5000 \frac{1-(1+0.04)^{-10}}{0.04} \approx 40554.48$$
(ii)
$$ PV= P \frac{1}{i} \\
     = 5000 \frac{1}{0.04} \approx 125000 $$

### Question 8 {- #eq3.8}

(a)As the rate is compounded semi-annually, the actual interest rate for 6 months is i=0.036/2=0.018 
$$ a = 2000(1+0.018)^2= 2000(1.018)^2\\
r = (1.018)^2\\
S = a \frac{(r)^{n}-1}{r-1}\\
     = 2000(1.018)^2\frac{(1.018)^{20}-1}{1.018^2-1}\\
     \approx 24464.35 $$
(b)As the rate is compounded semi-annually, the actual interest rate is i=0.045/2, and the actual year is doubled, that is: 
$$ 145000(1+0.045/2)^{-1\times2} + 80000(1+0.045/2)^{-2\times2}-200000 \\
   \approx 11876.26 $$

# Chapter 2 {- #s2}

## Multiple choice questions {- #mq2}


### Question 1 {- #mq2.1}

**Answer : B**

It is obvious to choose B.

### Question 2 {- #mq2.2}

**Answer : D**

As $$ 3x^2-7x+1 =0 $$
Then $$ x= \frac{-b \pm \sqrt{b^2-4ac}}{2a}\\
    = \frac{7 \pm \sqrt{37}}{6}$$

### Question 3 {- #mq2.3}

**Answer : C**

As $$ \pi = TR - TC ; TR=PQ$$
From the question, we can get $$ TC = 20+2Q $$
As $$ P+2Q=24 $$
Then $$P = -2Q+24 $$
$$ \pi = TR-TC \\
       = PQ-TC\\
       = (-2Q+24)Q-(20+2Q)\\
       = -2Q^2+22Q-20 $$

### Question 4 {- #mq2.4}

**Answer : B**

From the graph, we can get the expressions of the curves. TR is a quadratic equation about Q, TC is a first order equation about Q.You can substitute the value of the special points into the equation to solve the problem.
$$  TR = -2Q^2+200Q  $$
$$ TC = 55Q+500 $$
$$ \pi = TR-TC \\
       = (-2Q^2+200Q) - (55Q+500) \\
       = -2Q^2+145Q-500 $$
When $$ Q=-\frac{b}{2a}\\
         =\frac{145}{4} $$
Substitute the value of Q into the equation to get the maximum profit.
$$ \pi = -2\times (\frac{145}{4})^2+145\times \frac{145}{4}-500\\
       = 2128.125$$
It is closest to 2100, so we choose B.

### Question 5 {- #mq2.5}

**Answer : C**

$$ TC=300Q+80000 $$
When TC=123800
Then $$ 123800=TC=300Q+80000 $$
$$ Q=146 $$

### Question 6 {- #mq2.6}

**Answer : D**

$$ Q=f(K,L) $$ is said to be homogeneous if $$ f(\lambda K, \lambda L)=\lambda^n f(K,L) $$
As $$ f(K, L)= 8 \sqrt{L^2K}+2KL $$
$$ f(\lambda K, \lambda L)=8 \sqrt{(\lambda L)^2\lambda K}+2(\lambda K)(\lambda L) \\
  =8 \lambda^\frac{3}{2} \sqrt{L^2K}+2 \lambda^2 KL\\
  \neq\lambda^n f(K,L) $$
Thus, it is not homogeneous, we choose D.

### Question 7 {- #mq2.7}

**Answer : C**

As$$ TC=3Q^2+50 $$,
Thus $$ AC = \frac{TC}{Q}\\
           = 3Q+\frac{50}{Q} $$
          
It is obviously that we choose C.

### Question 8 {- #mq2.8}

**Answer : A**

$$ log_a14 - log_a7 +2log_ax - 3log_ay - log_a1  \\
  =log_a14 - log_a7 +log_ax^2 - log_ay^3 - 0 \\
  =log_a(\frac{14x^2}{7y^3})\\
  =log_a(\frac{2x^2}{y^3})$$

### Question 9 {- #mq2.9}

**Answer : A**

$$ 21x^2+cx-10 = 0 $$
Substitute the value of x=2/7 into the equation, we get c.
$$ 21(\frac{2}{7})^2+c\frac{2}{7}-10 = 0 $$
$$ c=29 $$
$$ 21x^2+29x-10 = 0 $$
$$ x= \frac{-29 \pm \sqrt{29^2-4\times21\times(-10)}}{2\times21} \\
    = \frac{-29 \pm 41}{42} \\
    = \frac{2}{7} or -\frac{5}{3}$$

### Question 10 {- #mq2.10}

**Answer : B**

As $$3P+2Q=60 $$
Thus $$ P=-\frac{2}{3}Q+20 $$
As $$ TC = 4Q+13   $$

$$ \pi=TR-TC\\
      =PQ-TC\\
      =(-\frac{2}{3}Q+20)Q-(4Q+13) \\
      =-\frac{2}{3}Q^2+16Q-13 $$
When $$ \pi =77 $$
Then $$ 77=-\frac{2}{3}Q^2+16Q-13 $$
$$ \frac{2}{3}Q^2-16Q+90=0 $$
$$ Q = \frac{16 \pm \sqrt{(-16)^2-4\times\frac{2}{3}\times90}}{2\times \frac{2}{3}}\\
     = 9or15$$

### Question 11 {- #mq2.11}

**Answer : D** 

As $$ P \geq 0  $$
Thus $$ P=15-2Q-Q^2 \geq 0 $$
This is a one-dimensional quadratic curve with a downward opening,we can get :
$$ -5\leq Q \leq 3  $$
As $$ Q \geq 0  $$
Thus $$ 0\leq Q \leq 3  $$
Thus the largest possible value Q is 3.

### Question 12 {- #mq2.12}

**Answer : E** 

$$  V(t)=Ae^{0.05t} $$
As when t=0, V(0)=50,so 
$$ 50=Ae^{0.05\times0}=A $$
$$ V(t)=50e^{0.05t} $$
$$ 175=50e^{0.05t} $$
$$ t=20ln(\frac{7}{2}) $$

### Question 13 {- #mq2.13}

**Answer : D**

$$ P=Q^2+8Q+25=-Q^2-7Q+273 $$
$$ 2Q^2+15Q-248=0 $$
$$ Q = \frac{-15 \pm \sqrt{15^2-4\times2     \times(-248)}}{2\times2} \\
     =8or-15.5 $$
As $$ Q \geq 0  $$
Then $$ Q=8 $$
$$ P=Q^2+8Q+25\\
    =153 $$
Thus, the equilibrium price is 153.

### Question 14 {- #mq2.14}

**Answer : B**

$$ -Q^2+7Q \geq 10 $$
$$ -Q^2+7Q-10 \geq 0 $$
This is a one-dimensional quadratic curve with a downward opening,we can get :
$$ 2\leq Q \leq 5 $$

### Question 15 {- #mq2.15}

**Answer : A**

$$  18e^{-3x}=2e^{-5x} $$
$$  ln({18e^{-3x}}) = ln({2e^{-5x}})$$
$$  ln18 -3x=ln2 -5x $$
$$ 2x = ln2-ln18 \\
      = ln{\frac{2}{18}}\\
      = ln{3^{-2}}\\
      = -2ln3 $$
$$ x = -ln3 $$

## Examination questions {- #eq2}


### Question 1 {- #eq2.1}

(a)$$ Q = 100K^{\frac{2}{3}}L^{\frac{1}{2}} \\
        = 100\times8^{\frac{2}{3}}25^{\frac{1}{2}} \\
        = 2000$$
(b)$$ Q = 9000\\
        = 100K^{\frac{2}{3}}L^{\frac{1}{2}} \\
        = 100\times27^{\frac{2}{3}}L^{\frac{1}{2}} \\
        = 900L^{\frac{1}{2}}  $$
   $$ L = 100 $$  
(c)$$ Q = 3200\\
        = 100K^{\frac{2}{3}}L^{\frac{1}{2}} \\
        = 100K^{\frac{2}{3}}4^{\frac{1}{2}} \\
        = 200K^{\frac{2}{3}}  $$
   $$ K = 64 $$
(d)$$ f(\lambda K, \lambda L)=100(\lambda K)^{\frac{2}{3}}(\lambda L)^{\frac{1}{2}} \\
      = \lambda^{\frac{7}{6}}100K^{\frac{2}{3}}L^{\frac{1}{2}} \\
      = \lambda^{\frac{7}{6}}f(K,L)$$
Thus this function is **homogeneous**.

As $$ n=\frac{7}{6}>1 $$
Thus this function is **increasing returns to scale**.

### Question 2 {- #eq2.2}

As $$ TC = 2Q+8;P=8-Q $$
Thus $$\pi = TR-TC\\
           = PQ-TC\\
           = (8-Q)Q-(2Q+8)\\
           = -Q^2+6Q-8 $$
The graph is omitted, you can refer to the answers in the textbook.

(a)When the firm break-even, the profit is equal to 0.
$$ \pi = 0\\
       = -Q^2+6Q-8 $$
$$ Q = 2 or 4 $$
(b)When $$ Q = -\frac{b}{2a}\\
             = -\frac{6}{-2}\\
             = 3$$
$$ \pi_{max}=-3^2+6\times3-8 \\
            = 1$$
Thus the maximum profit is 1.

(c)As $$ \pi = TR-TC=PQ-TC $$
When there is decrease in fixed costs, TC is decreased, profits is increased. And the fixed costs only affects the constant of the quadratic curve, so the curve shifts vertically upwards.

### Question 3 {- #eq2.3}

(a) $$  P=2Q^2+3Q+10=-Q^2-3Q+154 $$ 
$$  3Q^2+6Q-144 = 0  $$
$$ Q = 6 or -8 $$
As $$ Q \geq 0  $$
Then $$ Q=6 $$
$$ P = 2Q^2+3Q+10\\
     = 2\times6^2+3\times6+10 \\
     = 100$$
Thus the equilibrium price is 100 and the equilibrium quantity is 6.

(b)If there is a tax of $5 per item, the supply function is changed, that is :
$$ P-5 = 2Q_S^2+3Q_S+10$$
$$ P = 2Q_S^2+3Q_S+15 $$
$$ P = 2Q^2+3Q+15=-Q^2-3Q+154  $$
$$ 3Q^2+6Q-139 = 0  $$
$$ Q' = -1 \pm \frac{\sqrt{426}}{3}$$
As $$ Q \geq 0  $$
Then $$ Q=-1 + \frac{\sqrt{426}}{3}\\
         \approx 5.88$$
$$ P=2Q^2+3Q+15 \approx 101.79$$
Thus the new values of equilibrium price and quantity are 101.79 and 5.88(round).

The tax paid by consumer is $$ 101.79 - 100=1.79 $$
The tax paid by producer is $$100+5-101.79=3.21 $$

### Question 4 {- #eq2.4}

(a)$$ TR=PQ \\
        =(10-Q)Q\\
        =-Q^2+10Q$$
$$  \pi = TR-TC\\
        = (-Q^2+10Q)-(12+2Q)\\
        = -Q^2+8Q-12$$
(b)$$  \pi = -Q^2+8Q-12 \geq 3$$
$$  -Q^2+8Q-15 \geq 0$$
$$ 3 \leq Q \leq 5 $$
$$ P=10-Q $$
$$ Q=10-P $$
$$ 3 \leq 10-P \leq 5 $$
$$ 5 \leq P \leq 7 $$

### Question 5 {- #eq2.5}

(a)(i)$$ 5log_ax-2log_ay+log_axy\\
        =log_ax^5-log_ay^2+log_axy\\
        =log_a(\frac{x^5xy}{y^2})\\
        =log_a(\frac{x^6}{y})$$
   (ii)$$ log_25+\frac{1}{2}log_236-log_2120 \\
         =log_25+log_6-log_2120\\
         =log_2\frac{5\times6}{120}\\
         =log_2\frac{1}{4}\\
         =log_22^{-2}\\
         =-2$$
(b)$$ P=Ab^t  $$
$$ 1000=Ab^0\\
   1100=Ab^1\\
   1210=Ab^2 $$
$$ A=1000;b=1.1 $$
$$ P=10001.1^t  $$
(i)$$ P=10001.1^{10} \approx 2594$$
(ii)$$ P=10001.1^t \geq 8000 $$
$$ t\geq \frac{ln8}{ln1.1} \approx 21.817$$
Thus the number of complete years is **22**.

### Question 6 {- #eq2.6}

(a)$$TC = 2Q+14 $$
$$ AC = \frac{TC}{Q}\\
      = \frac{2Q+14}{Q}\\
      = 2+\frac{14}{Q} $$
The graphs are omitted.

(b)$$ \pi = TR-TC\\
          = PQ-TC\\
          = PQ-(2Q+14)\\
          = (P-2)Q-14$$
The constant in the profit function is -14 ,so c=-14.

(c)$$ \pi =aQ^2+bQ-14 $$
$$\begin{cases} -6=a+b-14\\ 4=36a+6b-14 \end{cases}$$
$$\begin{cases} a+b=8\\ 36a+6b=18 \end{cases}$$
$$\begin{cases} a=-1\\ b=9 \end{cases}$$

(d)$$ \pi =-Q^2+9Q-14 $$
When the profit is equal to 0, we can get the break-even points.
$$  \pi =-Q^2+9Q-14=0 $$
$$ Q=7or 2 $$
When $$Q=-\frac{b}{2a}=4.5 $$ 
$$ P= -4.5^2+9\times4.5-14 \\
    = 6.25$$
Thus the maximum profit is 6.25.

(e)$$ \pi = TR-TC = PQ-TC $$
$$ TR = \pi + TC \\
      = -Q^2+9Q-14+2Q+14\\
      = -Q^2+11Q $$
$$ PQ = TC = -Q^2+11Q  $$
$$ P=-Q+11 $$

### Question 7 {- #eq2.7}

(a)(i)$$ \frac{a^5b^3}{2} $$
(ii)$$4x^2y^4$$
(iii)$$6$$
(iv)$$log_b(\frac{xyxz}{\frac{x}{yz}})\\
    = log_b(xy^2z^2)$$
    
(b)$$3^x=2(5^x) $$
$$ xln3=ln2+xln5 $$
$$ x=\frac{ln2}{ln3-ln5} \approx -1.36$$

(c)(i)$$ S=2000000(1-e^{-0.4}) \\
          \approx 659360$$
(ii)$$S=2000000(1-e^{-0.2t}) \geq 1000000$$
$$ t \geq 5ln2\approx3.5$$
(iii) The graph is omitted. 

### Question 8 {- #eq2.8}

(a)$$ V=Ab^t $$
$$\begin{cases} 45125=Ab^2\\ 40725=Ab^4 \end{cases}$$
$$A= \frac{45125^2}{40725} \approx 50000$$
$$b = \sqrt{\frac{40725}{45125}} \approx 0.95 $$
A is the initial price.

(b)$$ V=Ae^{rt} $$
$$\begin{cases} 45125=Ae^{2r}\\ 40725=Ae^{4r} \end{cases}$$
$$ A =\frac{45125^2}{40725} \approx 50000$$
$$ r = 0.5ln(\frac{40725}{45125})\approx -0.051297 $$
(c)$$ V=Ae^{rt} $$
$$ lnV=lnA+rt \\
      \approx 10.82-0.051297t\\
      $$
It is obvious that the graph is a straight line, and the gradient is -0.051297 and the vertical intercept is 10.82.


### Question 9 {- #eq2.9}

(a)For IT: $$TC = 1+(0.04Q+0.5)Q$$
$$ AC = \frac{TC}{Q} \\
      = \frac{1}{Q}+0.04Q+0.5$$
      
For Retail: $$TC = 5+0.5Q$$
$$ AC = \frac{TC}{Q} \\
      = \frac{5}{Q}+0.5$$

For Printing: $$TC = Q$$
$$ AC = \frac{TC}{Q} \\
      = 1$$

(b)As AC of Printing is 1, this is a straight line, it is B; As AC of Retail is $$\frac{5}{Q}+0.5$$, AC decreases with the increase of Q, it is C;So graph of IT is A.

(c)$$ \frac{1}{Q}+0.04Q+0.5 < 1 $$
$$ \frac{1}{Q}+0.04Q-0.5 < 0 $$
$$ 0.04Q^2-0.5Q+1 < 0 $$
$$ 2.5 < Q < 10 $$ 

# Chapter 1 {- #s1}

## Multiple choice questions {- #mq1}

### Question 1 {- #mq1.1} 

**Answer : E**

Q is on the horizontal axis, so we transform the function:
$$ 3P+4Q=9 $$
Transposition of terms, we get: 
$$ 3P=-4Q+9 $$
Divide both sides by 3, we get:
$$ P=\frac{-4Q+9}{3}  $$
Simplify it:
$$ P=-\frac{4}{3}Q+3 $$
Thus, the slope of the line is **-4/3**.

When Q=0, we get P=3, so the intercept on the P-axis is **3**.

### Question 2 {- #mq1.2} 

**Answer : B**
$$ 5(3x-4y)-(2x-3y) $$
$$ =(15x-20y)-(2x-3y) $$
$$ = 15x-20y-2x+3y $$
$$ = 15x-2x-20y+3y $$
$$ = (15-2)x+(-20+3)y $$
$$ = 13x-17y $$
Thus, we choose B.

### Question 3 {- #mq1.3} 

**Answer : C**

Q is the quantity and must be greater than or equal to 0.
$$ Q\geq0 $$
Thus, $$ Q=4P-25\geq0 $$
$$ 4P\geq25 $$
$$ P\geq \frac{25}{4} $$
Thus, we choose C.

### Question 4 {- #mq1.4} 

**Answer : D**

$$ 2(x+3)-(5x+1)\geq4 $$
$$ (2x+6)-(5x+1)\geq4 $$
$$ 2x+6-5x-1\geq4 $$
$$ (2x-5x)+(6-1)\geq4 $$
$$ -3x+5\geq4 $$
Transposition of terms, we get: 
$$ 5-4\geq3x $$
$$ 1\geq3x $$
Divide both sides by 3, we get:
$$ \frac{1}{3}\geq x $$
Thus, we choose D.

### Question 5 {- #mq1.5} 

**Answer : A**

$$\begin{cases} 4x-2y =3\\ 6x-3y=4 \end{cases}$$ 
In order to solve the system of equations, multiply both sides of equation 1 by 3 and multiply both sides of equation 2 by 2, we get:
$$\begin{cases} 3(4x-2y) =3\times3\\ 2(6x-3y)=2\times4 \end{cases}$$ 
$$\begin{cases} 12x-6y =9\\ 12x-6y=8 \end{cases}$$
Equation 1 minus equation 2, we get:
$$ 0=1 $$
This is a meaningless equation. Thus, the simultaneous equations has no solution, we choose A.

### Question 6 {- #mq1.6} 

**Answer : A**

To get the equilibrium price, we calculate with simultaneous equations.
$$\begin{cases} P=-3Q+75\\ P=2Q+15 \end{cases}$$
Equation 1 minus equation 2, we get:
$$ 0=(-3Q+75)-(2Q+15) $$
$$ 0=-3Q+75-2Q-15 $$
$$ 0=-5Q+60 $$
$$ 5Q=60 $$
$$ Q=12 $$
Substitute the Q value into any equation (here we choose equation 1), we get the P value.
$$ P=-3\times 12 +75 $$
$$ P=39 $$
Thus, we choose A.

### Question 7 {- #mq1.7} 

**Answer : E**

As a fixed tax of $5 is imposed, so supply equation is changed to be :
$$ P-5=2Q+15 $$
$$ P=2Q+20 $$
To get the post-tax equilibrium price, we calculate with simultaneous equations.
$$\begin{cases} P=-3Q+75\\ P=2Q+20 \end{cases}$$
Equation 1 minus equation 2, we get:
$$ 0=(-3Q+75)-(2Q+20) $$
$$ 0=-3Q+75-2Q-20 $$
$$ 0=-5Q+55 $$
$$ 5Q=55 $$
$$ Q=11 $$
Substitute the Q value into any equation (here we choose equation 1), we get the P value.
$$ P=-3\times 11 +75 $$
$$ P=42 $$
Thus, we choose E.


### Question 8 {- #mq1.8} 

**Answer : B**

we get a and b with simultaneous equations.
$$\begin{cases} 6=a\times10+b\\ 4.5=a\times25+b \end{cases}$$
Equation 1 minus equation 2, we get:
$$ 6-4.5=(10-25)a $$
$$ 1.5=-15a $$
$$ a=-0.1$$
Substitute the a value into any equation (here we choose equation 1), we get the b value.
$$ 6=-0.1\times 10 + b$$
$$ 6=-1 + b$$
$$ b=7 $$
Thus, the function is:
$$ P=-0.1Q+7 $$
Substitute the Q=14 into the function, we get:
$$ P=-0.1\times14+7 $$
$$ P=5.6 $$
Thus, we choose B.

### Question 9 {- #mq1.9} 

**Answer : D**

As $$ Y=C+G+I $$
Substitute C,G,I into the function, we get:
$$ Y=(0.8Y+20)+30+90 $$
$$ Y-0.8Y=20+90+30 $$
$$ 0.2Y = 140 $$
$$ Y=700 $$
When government expenditure rises by 1 unit, in other words,**G=31**. Substitute C=0.8Y+20,G=31,I=90 into the function, we get:
$$ Y=C+G+I
    =0.8Y+20+31+90 $$
$$ 0.2Y = 151 $$
$$ Y=705 $$
As $$ 705-700=5 $$
So the change in the value of Y is 5. We choose D.

### Question 10 {- #mq1.10} 

**Answer : A**

As $$ Y=C+S $$
Substitute C=0.75Y+4,S=3.5 into the function, we get:
$$ Y=0.75Y+4+3.5 $$
$$ 0.25Y = 7.5 $$
$$ Y= 30 $$
Thus, we choose A.

### Question 11 {- #mq1.11} 

**Answer : D**

As you can see the graphs in the textbook, the slope of supply function is positive, so **a>0**;The slope of demand function is negative, so **c<0**;Both the demand function and the supply function are in the first quadrant, and he intercept on the P-axis is greater than 0 for the supply function and the demand function, so **b>0** and **d>0**. Also, in order to make the equilibrium to exist, **d>b**.

### Question 12 {- #mq1.12} 

**Answer : D**

$$ x=\frac{5y+12}{y+3} $$
$$ x(y+3)=5y+12 $$
$$ xy+3x=5y+12 $$
$$ xy-5y=12-3x $$
$$ (x-5)y=3(4-x) $$
$$ y = \frac{3(4-x)}{x-5} $$
Thus, we choose D.

### Question 13 {- #mq1.13} 

**Answer : C**

$$ \frac{4}{x+2} - \frac{1}{x-1}\\
 = \frac{4(x-1)-(x+2)}{(x+2)(x-1)}\\
 = \frac{4x-4-x-2}{(x+2)(x-1)}\\
 = \frac{3x-6}{(x+2)(x-1)}\\
 = \frac{3(x-2)}{(x+2)(x-1)}$$
Thus, we choose C.

### Question 14 {- #mq1.14} 

**Answer : E**

$$\begin{cases} ax+by=c\\ dx+ey=f \end{cases}$$
$$\begin{cases} d(ax+by)=cd\\ a(dx+ey)=af \end{cases}$$
$$\begin{cases} adx+bdy=cd\\ adx+aey=af \end{cases}$$
Equation 1 minus equation 2, we get:
$$ (bd-ae)y=cd-af $$
$$ y = \frac{cd-af}{bd-ae}\\
     = \frac{af-cd}{ae-bd}$$
Substitute y into any equation(we choose equation 1), we get:
$$ ax+b\frac{af-cd}{ae-bd}=c $$
$$ ax = c-b\frac{af-cd}{ae-bd}\\
      = \frac{c(ae-bd)-b(af-cd)}{ae-bd}\\
      = \frac{ace-bcd-abf+bcd}{ae-bd}\\
      = \frac{ace-abf}{ae-bd}\\
      = \frac{a(ce-bf)}{ae-bd}$$
Divide both sides by a, we get:
$$ x=\frac{ce-bf}{ae-bd}$$
Thus, we choose E.

### Question 15 {- #mq1.15} 

**Answer : A**

If the system of equations has infinitely many solutions, this shows that the number of equation elements is more than the number of equations.
$$\begin{cases} x-2y+5z=7\\ 2x+3y-2z=-3\\ 4x-y+8z=k \end{cases}$$
$$\begin{cases} 4(x-2y+5z)=4\times7\\ 2(2x+3y-2z)=-3\times2\\ 4x-y+8z=k \end{cases}$$
$$\begin{cases} 4x-8y+20z=28\\ 4x+6y-4z=-6\\ 4x-y+8z=k \end{cases}$$

Equation 2 minus equation 1, Equation 2 minus equation 3,we get:
$$\begin{cases} 7y-12z=-17\\ 7y-12z=-6-k \end{cases}$$
The number of equation elements is more than the number of equations, so the above two equations are equivalent, in other words,
$$ 7y-12z=-17=-6-k $$
$$ k=11 $$
Thus, we choose A.

### Question 16 {- #mq1.16}

**Answer : A**

As $$ Y=C+I+G+X-M $$
$$ Y=(0.7Y+100)+30+50+80-(0.1Y+50) $$
$$ Y=0.7Y+100+30+50+80-0.1Y-50 $$
$$ Y-0.7Y+0.1Y= 100+30+50+80-50 $$
$$ 0.4Y=210 $$
$$ Y=525 $$
Thus, we choose A.

### Question 17 {- #mq1.17}

**Answer : D**

$$\begin{cases} 3x+5y-z=-12\\ 2x-3y+2z=22\\ x+4y-3z=-10 \end{cases}$$
$$\begin{cases} 2(3x+5y-z)=-12\times2\\ 3(2x-3y+2z)=22\times3\\ 6(x+4y-3z)=-10\times6 \end{cases}$$
$$\begin{cases} 6x+10y-2z)=-24\\ 6x-9y+6z)=66\\ 6x+24y-18z)=-60 \end{cases}$$
Equation 1 minus equation 2, Equation 3 minus equation 2,we get:
$$\begin{cases} 19y-8z=-90\\ 33y-24z=-126 \end{cases}$$
$$\begin{cases} 3(19y-8z)=-90\times3\\ 33y-24z=-126 \end{cases}$$
$$\begin{cases} 57y-24z=-270\\ 33y-24z=-126 \end{cases}$$
Equation 1 minus equation 2,we get:
$$ 24y=-144 $$
$$ y=-6 $$
Substitute y into one of the equation(we choose equation 33y-24z=-126), we get:
$$ 33\times(-6)-24z=-126 $$
$$ z=-3 $$
Thus, we choose D.

### Question 18 {- #mq1.18}

**Answer : C**

As the price of a complementary good decreases, the demand of the good that we care about increases, the supply of the good doesn't shift.Thus, the demand curve of the good shifts right, and the equilibrium price and quantity both increases. We choose C.

## Examination questions {- #eq1}

### Question 1 {- #eq1.1}

**(a)**
The graphs are omitted, please refer to textbook answers(page 672 ).

**(b)**
The distance is **12**.

**(c)** 
EatMeNow : y=9+0.5x

Deliver4U: y=1.25x 
$$\begin{cases} y=9+0.5x\\ y=1.25x \end{cases}$$
Equation 1 minus equation 2,we get:
$$ 0=9+0.5x-1.25x\\
    =9-0.75x$$
$$ x=12 $$
It's the same answer you got in part (b).

### Question 2 {- #eq1.2}

**(a)**
When P=5, substitute P=5 into the demand function, we can get the quantity demand, that is:
$$ Q_D = 400-15\times5\\
       = 325 $$
When P=5, substitute P=5 into the supply function, we can get the quantity supply, that is:
$$ Q_S = -50+10\times5\\
       = 0 $$
When P=10, 
$$ Q_D = 400-15\times10\\
       = 250 $$
$$ Q_S = -50+10\times10\\
       = 50 $$
When P=15, 
$$ Q_D = 400-15\times15\\
       = 175 $$
$$ Q_S = -50+10\times15\\
       = 100 $$
When P=20, 
$$ Q_D = 400-15\times20\\
       = 100 $$
$$ Q_S = -50+10\times20\\
       = 150 $$
When P=25, 
$$ Q_D = 400-15\times25\\
       = 25 $$
$$ Q_S = -50+10\times25\\
       = 200 $$
The graphs are omitted, please refer to textbook answers(page 673 ).

**(b)**
$$\begin{cases} Q=400-15P\\ Q=-50+10P \end{cases}$$
Equation 1 minus equation 2,we get:
$$ 0=(400-15P)-(-50+10P)\\
    =450-25P $$
$$ P=18 $$
$$ Q=400-15P\\
    =400-15\times18\\
    =130 $$
Thus, the equilibrium price is 18 and the equilibrium quantity is 130.

**(c)**
As you can see in the graphs, to the left of the equilibrium point, when P<18, the demand curve is above the supply curve, there is excess demand.
 
**(d)**
When a fixed tax of $5 is imposed, the supply function is changed, the price in the supply function is reduced by 5 on each good, that is:
$$ Q_S = -50+10(P-5) \\
       = -100+10P$$
$$\begin{cases} Q=400-15P\\ Q=-100+10P \end{cases}$$
Equation 1 minus equation 2,we get:
$$ 0=(400-15P)-(-100+10P)\\
    =500-25P $$
$$ P=20 $$
$$ Q=400-15P\\
    =400-15\times20\\
    =100 $$
Thus, the new equilibrium price is 20 and the equilibrium quantity is 100.


### Question 3 {- #eq1.3}

**(a)**
P and Q are negatively correlated in the demand equation; P and Q are positively correlated in the supply equation.Thus, **the first equation represents the demand curve, and the second equation represents the supply curve.**

**(b)**

In order to get the values of slope and vertical intercept, we transform the equation.
$$ Q+3P=48 $$
$$ 3P=-Q+48 $$
$$ P=-\frac{Q}{3}+16 $$
Thus, the coefficient of Q is the slope, and when Q=0, the P value obtained is the vertical intercept.So for the demand curve, the slope is -1/3, the vertical intercept is 16.

**(c)**
$$\begin{cases} Q+3P=48\\ Q-2P=30 \end{cases}$$
Equation 1 minus equation 2,we get:
$$ 3P+2P=48-30 $$
$$ 5P=18 $$
$$ P=3.6 $$
Substitute P into one of the equation(we choose equation 1), we get:
$$ Q+3\times3.6=48 $$
$$ Q=37.2 $$
Thus, the equilibrium price is 3.6, the equilibrium quantity is 37.2.

### Question 4 {- #eq1.4}

**(a)**
As $$ Y=C+I+G $$
Substitute C,I,G into the function, we get:
$$ Y= (0.75Y_d+150)+100+250 \\
    = [0.75(Y-T)+150]+100+250\\
    = [0.75(Y-50)+150]+100+250\\
    = 0.75Y-0.75\times50+150+100+250$$
$$ Y-0.75Y=-37.5+150+100+250$$
$$ 0.25Y=462.5 $$
$$ Y=1850 $$
Thus, the equilibrium level of national income is 1850.

**(b)**
$$ Y = C+I+G\\
     = (0.75Y_d+150)+(I+G)\\
     = [0.75(Y-T)+150]+(I+G)\\
     = 0.75Y-0.75T+150+(I+G)$$
$$ 0.25Y = -0.75T+150+(I+G) $$
Substitute Y=1850+20=1870,T=50 into the function, we get:
$$ 0.25\times1870 = -0.75\times50+150+(I+G) $$
$$ I+G = 355 $$
The total increase in G and I is **5** as follows.
$$ 355-(100+250)=5 $$

### Question 5 {- #eq1.5}

**(a)**

Substitute K=40,L=30 into the function, we get:
$$ Q = \frac{KL}{K+2L}\\
     = \frac{40\times30}{40+2\times30}\\
     = \frac{1200}{100}\\
     = 12$$

**(b)**

Substitute Q=4,K=10 into the function, we get:
$$ 4 = \frac{10L}{10+2L}$$
$$ 40+8L = 10L $$
$$ 40 = 2L $$
$$ L=20 $$

**(c)**
$$ Q = \frac{KL}{K+2L}$$
$$ Q(K+2L)=KL $$
$$ QK+2QL=KL $$
$$ KL-QK=2QL $$
$$ K(L-Q)=2QL $$
$$ K=\frac{2QL}{L-Q} $$



### Question 6 {- #eq1.6}

**(a)**
$$ C+I=0.75Y+18+22\\
      =0.75Y+40 $$
When Y=0, 
$$ C+I = 0.75\times0+40\\
       =40 $$
When Y=100, 
$$ C+I = 0.75\times100+40\\
       =115 $$
When Y=200, 
$$ C+I = 0.75\times200+40\\
       =190 $$
       
The graphs are omitted, please refer to textbook answers(page 673 ).
$$ Y = C+I 
     = 0.75Y+40 $$

$$ 0.25Y=40 $$
$$ Y=160 $$
Thus, the equilibrium level of national income is **160**.

The equilibrium level of national income decreases, you can refer to textbook answers(page 673 ).

### Question 7 {- #eq1.7}

**(a)**
These goods are substitutable. As in the demand function for good 1, the coefficient of P2 is positive, which means that when the demand for good 1 rises, the price of good 2 increases so that the demand for good 2 decreases. It is the same in the demand function for good 2.

**(b)**
To get the equilibrium price and quantity,we use $$ Q_D = Q_S$$
$$\begin{cases} 120-2P_1+P_2=-7+7P_1\\ 168+3P_1-7P_2=-3+20P_2 \end{cases}$$
$$\begin{cases} 9P_1-P_2=127\\ 3P_1-27P_2=-171 \end{cases}$$
$$\begin{cases} 9P_1-P_2=127\\ 3(3P_1-27P_2)=-171\times3 \end{cases}$$
$$\begin{cases} 9P_1-P_2=127\\ 3(3P_1-27P_2)=-171\times3 \end{cases}$$
Equation 1 minus equation 2,we get:
$$80P_2=640 $$
$$ P_2 = 8 $$
Substitute the value into any equation (we choose equation 1)
$$ 120-2P_1+8 ==-7+7P_1 $$
$$ P_1=15 $$
$$ Q_1 = -7+7P_1\\
       = -7+7\times15\\
       = 98 $$
$$ Q_2 = -3+20P_2\\
       = -3+20\times8\\
       = 157 $$
The equilibrium price and quantity for good 1 are 15 and 98;The equilibrium price and quantity for good 2 are 8 and 157.

**(c)**
As there is a subsidy of $4 on good 1, the subsidy have effect on the supply function, so 
$$ P_1' = P_1 + 4 $$
So $$ Q_{D_1} = 120-2P_1+P_2  ;  Q_{S2} = -7+7{P_1}'\\
      Q_{D_1} = 168+3P_1-7P_2  ;  Q_{S2} = -3+20{P_2}$$
$$\begin{cases} 120-2P_1+P_2=-7+7(P_1+4)\\ 168+3P_1-7P_2=-3+20P_2 \end{cases}$$
$$\begin{cases} 9P_1-P_2=99\\ 3P_1-27P_2=-171 \end{cases}$$
$$\begin{cases} 9P_1-P_2=99\\ 3(3P_1-27P_2)=-171\times3 \end{cases}$$      
Equation 1 minus equation 2,we get:
$$80P_2=612$$
$$ P_2 = 7.65 $$
Substitute the value into any equation (we choose equation 1)
$$ 120-2P_1+P_2=-7+7(P_1+4) $$
$$ 120-2P_1+7.65=-7+7(P_1+4) $$
$$P_1 = 11.85 $$
$$11.85-15=-3.15 \\
  7.65-8=-0.35 $$
For good 1, the equilibrium price reduces by $3.15;For good 2, the equilibrium price reduces by $0.35.

### Question 8 {- #eq1.8} 

**(a)**       
$$ 3f+4s \leq 3000 $$
Substitute s=270 into the function, we get:
$$ 3f+4\times270 \leq 3000 $$
$$ 3f \leq 3000-4\times270  $$
$$ 3f\leq 1920  $$
$$ f \leq 640 $$
Thus, the maximum amount of flour is 640kg.
       
**(b)**

(i)$$ P=\frac{36}{2Q+5}\\
       =\frac{36}{2\times3.5+5}\\
       =\frac{36}{12}\\
       =3 $$
(ii)$$ P=2.4\\
        =\frac{36}{2Q+5}$$
    $$ 2.4(2Q+5)=36 $$
    $$ 4.8Q+12=36 $$
    $$ 4.8Q=24 $$
    $$ Q=5 $$
(iii)$$ P=\frac{36}{2Q+5} $$
     $$ P(2Q+5)=36 $$
     $$ 2PQ+5P=36 $$
     $$ 2PQ=36-5P $$
     $$ Q=\frac{36-5P}{2P} $$
**(c)**

As $$ Y=C+S $$
$$ S=Y-C\\
    =Y-\frac{Y^2 + 100}{Y+2}\\
    =\frac{Y(Y+2)-(Y^2 + 100)}{Y+2}\\
    =\frac{Y^2+2Y-Y^2-100}{Y+2}\\
    =\frac{2Y-100}{Y+2}$$
       
### Question 9 {- #eq1.9}

**(a)** 
Firstly, we get x and y expressed by m and n.
$$\begin{cases} 2x+6y=1\\ 3x+my=n \end{cases}$$      
$$\begin{cases} 3(2x+6y)=3\\ 2(3x+my)=2n \end{cases}$$      
Equation 1 minus equation 2,we get:
$$(18-2m)y=3-2n$$
$$ y=\frac{3-2n}{2(9-m)}$$
Substitute the value of y into any equation (we choose equation 1)
$$ 2x+6(\frac{3-2n}{2(9-m)}) =1$$
$$ x= \frac{6n-m}{2(9-m)} $$
Thus, when m=9, the system fail to possess a unique solution.

When m=9,
$$\begin{cases} 2x+6y=1\\ 3x+9y=n \end{cases}$$      
$$\begin{cases} 2x+6y=1\\ \frac{2}{3}(3x+9y)=\frac{2}{3}n \end{cases}$$ 
$$\begin{cases} 2x+6y=1\\ 2x+3y=\frac{2}{3}n\end{cases}$$ 
Equation 1 minus equation 2,we get:
$$ 0 = 1-\frac{2}{3}n $$
When m=9, n = 1.5, the above equation(0=1-2/3n) exits, the two equations in the system of equations are equivalent, so the system has infinite solutions;When$$ m=9, n \neq1.5$$, the above equation(0=1-2/3n) doesn't exit, the system doesn't have any solution.

**(b)**
$$\begin{cases} 5P_1-3P_2=39\\ 2P_1+4P_2-3P_3=28\\ 3P_2+P_3=29 \end{cases}$$ 
$$\begin{cases} 5P_1-3P_2=39\\ 2P_1+4P_2-3P_3=28\\ 3(3P_2+P_3)=29\times3 \end{cases}$$ 
Equation 2 plus equation 3,we get:
$$\begin{cases} 5P_1-3P_2=39\\ 2P_1+13P_2=115 \end{cases}$$ 
$$\begin{cases} 2(5P_1-3P_2)=78\\ 5(2P_1+13P_2)=575 \end{cases}$$ 
Equation 2 minus equation 1,we get:
$$ 71P_2=497 $$
$$ P_2=7 $$
As$$ 5P_1-3P_2=39 $$
$$ 5P_1 -3 \times 7 =39 $$
$$ P_1 =12 $$
As $$ 3P_2+P_3=29 $$
$$ 3\times7+P_3=29 $$
$$ P_3 = 8 $$

### Question 10 {- #eq1.10}

**(a)**      
As $$ Y=C+I;M_S=L_1+L_2 $$
$$\begin{cases} Y=(0.6Y+60)+(-40r+1300)\\ 600=0.2Y+(-30r+40) \end{cases}$$
$$\begin{cases} 0.4Y=-40r+1360\\ 0.2Y=30r+560 \end{cases}$$       
$$\begin{cases} 0.5(0.4Y)=0.5(-40r+1360)\\ 0.2Y=30r+560 \end{cases}$$          
$$\begin{cases} 0.2Y=-20r+680\\ 0.2Y=30r+560 \end{cases}$$           
Equation 2 minus equation 1,we get:
$$ 0 = 50r-120 $$
$$ r = 2.4 $$
As$$ 600=0.2Y+(-30r+40) $$
$$Y=3160$$
The equilibrium values of Y and r will decrease when the MPC decreases. As the MPC decreases, the slope of the function(C = 0.6Y+60) decreases, we assume it decreases to be a, then a<0.6 .
As $$ Y=C+I\\
       =aY+60-40R+1300$$
   $$(1-a)Y=-40r+1360 $$
   $$Y = \frac{-40}{1-a}r+\frac{1360}{1-a} $$
When we draw a LM-IS curves(refer to the textbook on page 674), the slope of IS curve increases, the curve moves  to the lower left.So the equilibrium values of Y and r will decrease when the MPC decreases.

     
       


